[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=1A790B956C8B40559F99CA09D1BBB4F3
ProjectName=Kubostrel
CompanyName=Mhlgvr
ProjectVersion=1.0.0
bShouldWindowPreserveAspectRatio=True
bUseBorderlessWindow=False
bStartInVR=False

[/Script/UnrealEd.ProjectPackagingSettings]
BuildConfiguration=PPBC_Development
bUseIoStore=True
bShareMaterialShaderCode=True
bSharedMaterialNativeLibraries=True
bCompressed=True
IncludeDebugFiles=False
bSkipEditorContent=True
bGenerateChunks=False
ForDistribution=False
+MapsToCook=(FilePath="/Engine/Maps/Entry")
+DirectoriesToAlwaysCook=(Path="/Game/KS")
+DirectoriesToAlwaysCook=(Path="/Engine/BasicShapes")
; Fonts used by the canvas UI (Roboto has Cyrillic letters).
+DirectoriesToAlwaysCook=(Path="/Engine/EngineFonts")
